[package]
name = "pw-eq"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
clap = { version = "4.5.53", features = ["derive"] }
dirs = "6.0.0"
pw-util = { version = "0.1.0", path = "../pw-util" }
tabled = "0.20.0"
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros"] }
