[package]
name = "spa-json"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = "2.12.1"
itoa = "1.0.17"
libspa-sys = "0.9.2"
memchr = "2.7.6"
ryu = "1.0.22"
serde.workspace = true

[dev-dependencies]
expect-test = "1.5.1"
serde = { workspace = true, features = ["derive"] }
